#!/bin/bash

declare -a arr=("jackson" "theo" "nicolas")

for i in {0..49}
do
	for j in {0..9}
	do
		for k in "${arr[@]}"	
		do
			file="${k}/${k}_${j}_${i}.wav"	
			sox train/$file -r 8000 train/$file
			sox test/$file -r 8000 test/$file
		done
	done
done
