#!/bin/bash

cd recordings

declare -a arr=("jackson" "theo" "nicolas")

for i in "${arr[@]}"
do
	mkdir $i
done

for i in {0..49}
do
	for j in {0..9}
	do
		for k in "${arr[@]}"	
		do
			end=".wav"
			file="${j}_${k}_${i}${end}"	
			mv $file $k/$file
		done
	done
done
