#!/bin/bash

rm utt2spk
touch utt2spk

declare -a arr=("jackson" "theo" "nicolas")

for i in {0..49}
do
	for j in {0..9}
	do
		for k in "${arr[@]}"	
		do
			utterance="${k}_${j}_${i}"	
			echo "$utterance $k" >> utt2spk

		done
	done
done
