#!/bin/bash
 
rm text
touch text
 
declare -a arr=("jackson" "theo" "nicolas")
declare -A map=( [0]="zero" [1]="one" [2]="two" [3]="three" [4]="four" [5]="five" [6]="six" [7]="seven" [8]="eight" [9]="nine" )
 
for i in {0..49}
do
	for j in {0..9}
	do
		for k in "${arr[@]}"	
		do
			utterance="${j}_${k}_${i}"	
			echo "$utterance ${map[$j]}" >> text
 
		done
	done
done

