#!/bin/bash
 
rm wav.scp
touch wav.scp
 
declare -a arr=("jackson" "theo" "nicolas")
user="mfb33"
 
 
for i in {0..49}
do
	for j in {0..9}
	do
		for k in "${arr[@]}"	
		do
			end=".wav"
			utterance="${j}_${k}_${i}"	
			path="/home/$user/kaldi/egs/digits/digits_audio/train/"
			file="$path${k}/$utterance$end"
			echo "$utterance $file" >> wav.scp
 
		done
	done
done

